language: python
python:
  - "2.6"
  - "2.7"

install: pip install -r requirements.txt --use-mirrors
before_script:  python setup.py pep8
script:  python setup.py test

notifications:
  email:
    - farscape-dev@lists.rackspace.com
